### ISSUE TITLE
opinion DBテーブルを作成する

### ISSUE THREAD

**Issue by arith-k-saito** [arith-alexander/opinion_frontend#6]
opinionのDBテーブルを作成する

**Comment by arith-k-saito** [comment]
必要なテーブルは下記の通り
Frontend DB
- [x] opinion(アンケート)
- [x] question(設問)
- [x] choice(選択肢)
- [x] free_answer(自由回答結果)
- [x] choice_answer(選択肢回答結果)
- [x] user(ユーザー情報)

Admin DB
- [x] admin_user(管理ツールユーザー)

**Comment by arith-k-saito** [comment]
issue立てたので上のチェックボックスは使用しない
